#!/bin/sh
#
# Installs Claude Faces Expert for OpenAI Codex.
# This is a wrapper around install.sh that adds Codex-specific configuration.
#
# Codex loads AGENTS.md as literal text and does not resolve references to
# other files, so the rules are inlined between markers. Re-running replaces
# that block and leaves the rest of the file untouched.
#
# Usage:
#   # Project install (into ./.claude/ + ./AGENTS.md + ./.agents/skills/):
#   curl -sL https://raw.githubusercontent.com/omnifaces/claude-faces-expert/main/install-codex.sh | sh
#
#   # User install (into ~/.claude/ + ~/.codex/AGENTS.md + ~/.agents/skills/):
#   curl -sL https://raw.githubusercontent.com/omnifaces/claude-faces-expert/main/install-codex.sh | sh -s -- --user
#

set -e

if [ "$1" = "--user" ]; then
    SCOPE="user"
    RULES="$HOME/.claude/faces/rules.md"
    TOPICS="~/.claude/faces/topics/"
    SKILLS_SRC="$HOME/.claude/skills"
    AGENTS_MD="$HOME/.codex/AGENTS.md"
    SKILLS_DIR="$HOME/.agents/skills"
    curl -fsSL https://raw.githubusercontent.com/omnifaces/claude-faces-expert/main/install.sh | sh -s -- --user
else
    SCOPE="project"
    RULES=".claude/faces/rules.md"
    TOPICS=".claude/faces/topics/"
    SKILLS_SRC=".claude/skills"
    AGENTS_MD="AGENTS.md"
    SKILLS_DIR=".agents/skills"
    curl -fsSL https://raw.githubusercontent.com/omnifaces/claude-faces-expert/main/install.sh | sh
fi

BEGIN_MARKER="<!-- BEGIN Jakarta Faces Expert -->"
END_MARKER="<!-- END Jakarta Faces Expert -->"

echo "Configuring Codex..."

mkdir -p "$(dirname "$AGENTS_MD")"
TMP_FILE=$(mktemp)

if [ -f "$AGENTS_MD" ]; then
    if grep -qF "$BEGIN_MARKER" "$AGENTS_MD" && ! grep -qF "$END_MARKER" "$AGENTS_MD"; then
        rm -f "$TMP_FILE"
        echo "ERROR: $AGENTS_MD has a begin marker without a matching end marker." >&2
        echo "  Restore the '$END_MARKER' line or delete the block by hand, then re-run." >&2
        exit 1
    fi
    awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" \
        '$0 == begin { skip = 1; next } $0 == end { skip = 0; next } !skip' "$AGENTS_MD" > "$TMP_FILE"
    ACTION="Updated"
else
    printf '# Agent Notes\n' > "$TMP_FILE"
    ACTION="Created"
fi

{
    printf '\n%s\n\n' "$BEGIN_MARKER"
    printf 'Generated by install-codex.sh. Do not edit; re-run the installer to update.\n\n'
    printf 'Before answering any question about Jakarta Faces (JSF), conceptual ones included, follow the rules below.\n'
    printf 'For detailed guidance, read the referenced topic file under `%s` before answering.\n\n' "$TOPICS"
    cat "$RULES"
    printf '\n%s\n' "$END_MARKER"
} >> "$TMP_FILE"

cat "$TMP_FILE" > "$AGENTS_MD"
rm -f "$TMP_FILE"
echo "$ACTION $AGENTS_MD"

mkdir -p "$SKILLS_DIR"
cp -r "$SKILLS_SRC/"* "$SKILLS_DIR/"
echo "Copied skills to $SKILLS_DIR/"

echo "Codex configuration complete ($SCOPE scope)"
echo ""
echo "Codex does not read .claude/skills/, so the skills are copied to"
echo "$SKILLS_DIR/; re-run this installer to update them."
