#!/bin/sh
#
# Installs Claude Faces Expert for GitHub Copilot.
# This is a wrapper around install.sh that adds Copilot-specific configuration.
#
# Copilot does not follow references to other files from its instructions file,
# so the rules are inlined into .github/copilot-instructions.md between markers.
# Re-running replaces that block and leaves the rest of the file untouched.
#
# Usage:
#   # Project install (into ./.claude/ + ./.github/copilot-instructions.md):
#   curl -sL https://raw.githubusercontent.com/omnifaces/claude-faces-expert/main/install-copilot.sh | sh
#

set -e

if [ "$1" = "--user" ]; then
    echo "ERROR: Copilot instructions are per-repository; there is no supported user scope." >&2
    echo "  Run without --user from your project root." >&2
    exit 1
fi

curl -fsSL https://raw.githubusercontent.com/omnifaces/claude-faces-expert/main/install.sh | sh

RULES=".claude/faces/rules.md"
COPILOT_MD=".github/copilot-instructions.md"
BEGIN_MARKER="<!-- BEGIN Jakarta Faces Expert -->"
END_MARKER="<!-- END Jakarta Faces Expert -->"

echo "Configuring Copilot..."

mkdir -p "$(dirname "$COPILOT_MD")"
TMP_FILE=$(mktemp)

if [ -f "$COPILOT_MD" ]; then
    if grep -qF "$BEGIN_MARKER" "$COPILOT_MD" && ! grep -qF "$END_MARKER" "$COPILOT_MD"; then
        rm -f "$TMP_FILE"
        echo "ERROR: $COPILOT_MD has a begin marker without a matching end marker." >&2
        echo "  Restore the '$END_MARKER' line or delete the block by hand, then re-run." >&2
        exit 1
    fi
    awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" \
        '$0 == begin { skip = 1; next } $0 == end { skip = 0; next } !skip' "$COPILOT_MD" > "$TMP_FILE"
    ACTION="Updated"
else
    printf '# Copilot Instructions\n' > "$TMP_FILE"
    ACTION="Created"
fi

{
    printf '\n%s\n\n' "$BEGIN_MARKER"
    printf 'Generated by install-copilot.sh. Do not edit; re-run the installer to update.\n\n'
    printf 'Before answering any question about Jakarta Faces (JSF), conceptual ones included, follow the rules below.\n'
    printf 'For detailed guidance, read the referenced topic file under `.claude/faces/topics/` before answering.\n\n'
    cat "$RULES"
    printf '\n%s\n' "$END_MARKER"
} >> "$TMP_FILE"

cat "$TMP_FILE" > "$COPILOT_MD"
rm -f "$TMP_FILE"
echo "$ACTION $COPILOT_MD"

echo "Copilot configuration complete (project scope)"
echo ""
echo "The rules are inlined, so they apply in both ask and agent mode."
echo "The topic files stay referenced; agent mode reads them on demand."
